### ISSUE TITLE
Training Environment

### ISSUE THREAD

**Issue by snoop2head** [ds-wook/ml-project#1]
안녕하세요,

해당 프로젝트를 Train시키는 데 사용된 컴퓨팅 리소스에 대해서 여쭤보고 싶습니다. 
GPU/CPU/RAM 스펙 등에 대해서 간단히 알 수 있을까요?

감사합니다.

**Comment by ds-wook** [comment]
kaggle 노트북의 GPU, i7-10700 CPU, 램 32GB 컴퓨터에서 작업했습니다.
GPU는 구글 Colab Pro 쓰셔도 될꺼 같아요.

**Comment by snoop2head** [comment]
아하, 알려주셔서 감사합니다! 콜랩 프로는 안타깝게도 구글 드라이브에서 attach할 수 있는 사진의 개수가 제한되어 있더라구요 ㅠㅠ
감사해요!
